name: simple-pipeline

on:
 push:
    branches: [main]
        
jobs: 
    lintTest:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v2
            - name: Install Dependencies
              run: |
                echo "Running Install Dependencies..."
                npm install
            - name: Run Linting
              run: |
                echo "Running Linting tests..."
                npm run lint
              env:
                CI: true
    securityCheck:
        name: Security Check
        runs-on: ubuntu-latest
        steps:
         
            - name: Check for Security
              run: |
                echo "Running Security Checks 1..."
                sleep 5s;
                echo "Running Security Checks 2..."
                sleep 5s;
                echo "Running Security Checks 3..."
                sleep 5s;
                echo "Running Security Checks 4..."
                sleep 5s;
    deploy:
        name: Deployment
        runs-on: ubuntu-latest
        needs: [lintTest, securityCheck]
        steps:
            - name: Install Dependencies
              run: |
                echo "Deployment in progress..."
               